### ISSUE TITLE
[BUG] CarPlay resets to 0:00 frequently

### ISSUE THREAD

**Issue by sevenlayercookie** [LeoKlaus/plappa#142]
**Describe the bug**

**UPDATE**: this seems to possibly only be reproducible with _downloaded_ audiobooks.

CarPlay (and lockscreen and control center mini player) seekbar frequently resets to 0:00 when using the app and CarPlay simultaneously.

**To Reproduce**
1. Close Plappa on phone
2. Open Plappa on CarPlay
3. Play audiobook on CarPlay
4. Open Plappa on phone
5. Press play button on phone app
6. Watch CarPlay reset to zero

**Expected behavior**
CarPlay and phone app should remain synced, regardless of which controls are used.

**Screenshots**
_this demonstrates on the Lock Screen, since the CarPlay screen and the Lock Screen behave the same in this situation_

https://github.com/LeoKlaus/plappa/assets/15989705/09a2120b-3c6f-4cfa-a7b8-c3a641a973fa

**Logs**
Logs seem unrevealing

<details>
  <summary>Logs</summary>

```

[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:42 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully posted session
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:43 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates
[6/26/2024, 10:44 PM] [AudioBookShelfAPIHandler] Successfully pushed playbackstates

```

</details>

**Environment(please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 18 beta 2
 - Version 1.3.0 (13)
 - Server Version ABS 2.9.0

**Additional context**
- the correct timestamp does flash on CarPlay and Lockscreen for 0.5 seconds before resetting to 0 again
- If I start the book from CarPlay and control it **only** from CarPlay and Lockscreen, then no issues (pause/play/skip are all fine), but as soon as I control from the within the app on the phone, the bug occurs, and won't stop until I completely exit the app and restart only using CarPlay.

- Skip forward and backward frequently triggers the bug as well.

- After resetting to 0:00, if I resume playback using CarPlay or lockscreen, problem seems to sort of resolve, except:
- -  skip forward/back resets to zero
- - if I resume playback from the app, it stays at 0:00 on CarPlay ).

**Comment by LeoKlaus** [comment]
Thank you for the detailed report.
Even with your instructions, I haven't been able to reproduce this once (I'm also on 18 beta 2). Is this behavior reliably reproducible on your device using the steps?

I've just pushed a very small update to TestFlight (1.3.0. build 14), that removed a redundant setting of the now playing information. Can you check if this changes anything?

**Comment by sevenlayercookie** [comment]
> Thank you for the detailed report.
> 
> Even with your instructions, I haven't been able to reproduce this once (I'm also on 18 beta 2). Is this behavior reliably reproducible on your device using the steps?
> 
> 
> 
> I've just pushed a very small update to TestFlight (1.3.0. build 14), that removed a redundant setting of the now playing information. Can you check if this changes anything?

Won't be at my CarPlay enabled car for a week or so to test, but it looks like the issue still happens in the Lock Screen and control center even if I'm not connected to CarPlay. I'm on the new build you pushed.

**Comment by sevenlayercookie** [comment]
@LeoKlaus I have noticed that this bug seems to only affect downloaded audiobooks (e.g. same audiobook works fine when streaming, but as soon as I download, it does the skipping bug.

Have you tried to reproduce this bug with a downloaded Audiobook?

**Comment by LeoKlaus** [comment]
Thank you very much for the update! I'll see if I can reproduce it that way.

Regardless, this information is very valuable.

**Comment by rmusic10891** [comment]
I have also been experiencing this, on version 1.4. Happy to share any information you need.

**Comment by LeoKlaus** [comment]
I was finally able to reproduce this with a downloaded book. I've just released an update to TestFlight that should fix the issue (and some other issues causing the displayed time to be wrong).

Let me know if it worked :)

**Comment by sevenlayercookie** [comment]
Nicely done, that solved it! Thank you! Cheers
