### ISSUE TITLE
[BUG] VoiceOver issues in the app

### ISSUE THREAD

**Issue by BrailleBennett** [LeoKlaus/plappa#372]
I am a fully blind user of the app, and I wanted to report the overall minor voice over issues to you, aside from what is described in #300, which also effects me, so you could look into them further.
- The download button has no accessibility label right now
- All previously finished chapters of a book have the "selected" attribute applied to the button, I'd assume this is for visual styling, but is horrible UX for voice over users and should be replaced with a custom attribute/label to show completed status
- Past and current chapters of a book are missing their chapter numbers in the book screen
- There's elements on the player screen for "volume lowest" and "volume highest" that are labeled as images and appear not to do anything when clicked
- There's an unlabeled image next to the total time on the book overview page that says "person wave 2" as the default label
- The add to reading list button is just labeled as "add" leading to button functionality confusion
- Every option in the settings menu is missing the button attribute, leading to confusion over what is actually clickable

**Comment by BrailleBennett** [comment]
Related to #300

**Comment by LeoKlaus** [comment]
Thank you a ton for the detailed list! I think I got everything, I just released an update to the TestFlight version of plappa (build 71) including the changes. If you're not already using the TestFlight version, you can join here: https://testflight.apple.com/join/oSAekRD5

**Comment by BrailleBennett** [comment]
This new build is loads better. The only thing I can still reproduce is
- Every option in the settings menu is missing the button attribute, leading to confusion over what is actually clickable

**Comment by johanntan** [comment]
Hi,
I think the *finished* before each chapter should just be not spoken, it just adds more verbocity in my opinion.
