### ISSUE TITLE
[BUG] audiobookshelf: cannot log in with no library

### ISSUE THREAD

**Issue by kgraefe** [LeoKlaus/plappa#75]
**Describe the bug**
I set up a fresh audiobookshelf instance and did not create a library yet. When trying to connect, Plappa fails with no message.

As soon as I create a library, the login works (the debug log contained a hint).

**To Reproduce**
1. Create new audiobookshelf instance (don't create any library)
2. Start fresh install of Plappa
3. Try to connect

**Expected behavior**
Either login and handle the empty library list gracefully or at least show an appropriate error message

**Logs**

```
[25.4.2024, 11:59] [CoreDataHandler] Initializing core data store...
[25.4.2024, 11:59] [CoreDataHandler] CoreData store initialized
[25.4.2024, 11:59] [AudioBookShelfAPIHandler] Tried to init ABS APIHandler without server url or username
[25.4.2024, 11:59] [AudioBookShelfAPIHandler] Tried to init ABS APIHandler without server url or username
[25.4.2024, 11:59] [JellyfinAPIHandler] Couldn't connect to server: Could not connect to the server.
[25.4.2024, 11:59] [JellyfinAPIHandler] Couldn't connect to server: Could not connect to the server.
[25.4.2024, 11:59] [AudioBookShelfAPIHandler] Couldn't connect to server: Could not connect to the server.
[25.4.2024, 11:59] [plappa] Encountered an error while decoding auth response: The data couldn’t be read because it is missing.
valueNotFound(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "userDefaultLibraryId", intValue: nil)], debugDescription: "Cannot get unkeyed decoding container -- found null value instead", underlyingError: nil))
```

**Environment(please complete the following information):**
 - Device: iPhone SE2
 - OS: iOS17.4.1
 - Version: plappa 1.1.3
 - Server Version: audiobookshelf 2.9.0

**Additional context**

**Comment by LeoKlaus** [comment]
Hey Konrad, thanks for reporting this!

I think `userDefaultLibraryId` is set once you log in to web interface with a user. After that you should be able to log in with plappa.

I'll make sure to fix this with the next update!

**Comment by LeoKlaus** [comment]
I've already committed the fix, it'll release with the next update.

**Comment by kgraefe** [comment]
> I think userDefaultLibraryId is set once you log in to web interface with a user.

No, I did that and it did not resolve the issue. Creating a library did.

**Comment by LeoKlaus** [comment]
Thanks for the update.

**Comment by chancez** [comment]
I'm running into the same issue after deleting a library in my audiobookshelf install. I have another library instead, but I still can't login. The error is very similar:

```
[8/25/2024, 4:33 PM] [plappa] Encountered an error while decoding auth response: The data couldn’t be read because it is missing.
valueNotFound(Swift.Float, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "mediaProgress", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "duration", intValue: nil)], debugDescription: "Cannot get unkeyed decoding container -- found null value instead", underlyingError: nil))
```

Uninstalling the app and reinstalling doesn't help either.

**Comment by chancez** [comment]
Deleting and recreating my user did work-around it; though obviously that's a bit unfortunate as it will lose all the user's state.

**Comment by chancez** [comment]
@LeoKlaus can this be re-opened?

**Comment by LeoKlaus** [comment]
Hey Chance, this is a different issue. I've implemented a fix for this specific error but it's hard to tell what other keys will go missing when you delete a library. According to the [API documentation, this value is not supposed to be null](https://api.audiobookshelf.org/#media-progress).

**Comment by chancez** [comment]
Should we file a bug upstream? It's unclear what you're doing/expecting vs what the API is returning so it's a bit hard to provide them details in the issue.
